version: 1
disable_existing_loggers: False
formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%S"

handlers:
    console: # screen display print out
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout
    
    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: mth5_debug.log
        mode: 'w'
        maxBytes: 2485760 # 10MB
        backupCount: 5
    
    warning_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: standard
        filename: mth5_warning.log
        mode: 'w'
        maxBytes: 2485760 # 10MB
        backupCount: 5

loggers:
    __main__:
        level: DEBUG
        handlers: [console, debug_file_handler, warning_file_handler]
        propagate: no

root:
    level: DEBUG
    handlers: [console, debug_file_handler, warning_file_handler]
    propogate: yes
